CREATE TABLE IF NOT EXISTS organizations (id TEXT PRIMARY KEY,name TEXT NOT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY,email TEXT NOT NULL UNIQUE,name TEXT,password_hash TEXT NOT NULL,language TEXT NOT NULL DEFAULT '',created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS memberships (id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,user_id TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'operator',status TEXT NOT NULL DEFAULT 'pending',created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,approved_at DATETIME,FOREIGN KEY (organization_id) REFERENCES organizations(id),FOREIGN KEY (user_id) REFERENCES users(id),UNIQUE (organization_id,user_id));
CREATE TABLE IF NOT EXISTS organization_invites (id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,token TEXT NOT NULL UNIQUE,active BOOLEAN NOT NULL DEFAULT TRUE,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY (organization_id) REFERENCES organizations(id));
CREATE TABLE IF NOT EXISTS places (id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,name TEXT NOT NULL,token TEXT NOT NULL UNIQUE,active BOOLEAN NOT NULL DEFAULT TRUE,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY (organization_id) REFERENCES organizations(id));
CREATE TABLE IF NOT EXISTS products (id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,name TEXT NOT NULL,code TEXT NOT NULL,unit TEXT NOT NULL DEFAULT 'units',color TEXT NOT NULL DEFAULT '',active BOOLEAN NOT NULL DEFAULT TRUE,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY (organization_id) REFERENCES organizations(id),UNIQUE (organization_id,code));
CREATE TABLE IF NOT EXISTS qr_commands (id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,place_id TEXT NOT NULL,product_id TEXT NOT NULL,action TEXT NOT NULL,amount INTEGER NOT NULL,token TEXT NOT NULL UNIQUE,active BOOLEAN NOT NULL DEFAULT TRUE,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY (organization_id) REFERENCES organizations(id),FOREIGN KEY (place_id) REFERENCES places(id),FOREIGN KEY (product_id) REFERENCES products(id),UNIQUE (organization_id,place_id,product_id,action,amount));
CREATE TABLE IF NOT EXISTS inventory_events (id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,place_id TEXT NOT NULL,product_id TEXT NOT NULL,user_id TEXT NOT NULL,quantity_delta INTEGER NOT NULL,event_type TEXT NOT NULL,reversed_event_id TEXT,note TEXT,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY (organization_id) REFERENCES organizations(id),FOREIGN KEY (place_id) REFERENCES places(id),FOREIGN KEY (product_id) REFERENCES products(id),FOREIGN KEY (user_id) REFERENCES users(id),FOREIGN KEY (reversed_event_id) REFERENCES inventory_events(id));
CREATE TABLE IF NOT EXISTS sessions (token TEXT PRIMARY KEY,user_id TEXT NOT NULL,csrf TEXT NOT NULL,expires_at DATETIME NOT NULL);

CREATE TABLE IF NOT EXISTS print_qr_codes (id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,label TEXT NOT NULL,kind TEXT NOT NULL,place_id TEXT,product_id TEXT,qr_command_id TEXT,position INTEGER NOT NULL DEFAULT 0,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY (organization_id) REFERENCES organizations(id),FOREIGN KEY (place_id) REFERENCES places(id),FOREIGN KEY (product_id) REFERENCES products(id),FOREIGN KEY (qr_command_id) REFERENCES qr_commands(id));
CREATE INDEX IF NOT EXISTS idx_print_qr_codes_org ON print_qr_codes(organization_id,position,created_at);CREATE INDEX IF NOT EXISTS idx_memberships_user ON memberships(user_id);CREATE INDEX IF NOT EXISTS idx_memberships_org_status ON memberships(organization_id,status);CREATE INDEX IF NOT EXISTS idx_places_org ON places(organization_id);CREATE INDEX IF NOT EXISTS idx_products_org ON products(organization_id);CREATE INDEX IF NOT EXISTS idx_qr_commands_token ON qr_commands(token);CREATE INDEX IF NOT EXISTS idx_qr_commands_org_place ON qr_commands(organization_id,place_id);CREATE INDEX IF NOT EXISTS idx_inventory_events_org_created ON inventory_events(organization_id,created_at);CREATE INDEX IF NOT EXISTS idx_inventory_events_place_product ON inventory_events(place_id,product_id);CREATE INDEX IF NOT EXISTS idx_inventory_events_reversed ON inventory_events(reversed_event_id);
